### ISSUE TITLE
Time of load: 16.47sec , it takes so much, why?

### ISSUE THREAD

**Issue by xuxilei** [pg-strom/devel#266]
test=# EXPLAIN ANALYZE SELECT cat, count(*), avg(ax) FROM t0 NATURAL JOIN t1 GROUP BY cat;

                                                                     QUERY PLAN                                                                    

-----------------------------------------------------------------------------------------------------------------------------------------------------

HashAggregate  (cost=3602815.43..3602815.75 rows=26 width=12) (actual time=18345.727..18345.736 rows=26 loops=1)

   Group Key: t0.cat

   ->  Custom Scan (GpuPreAgg)  (cost=14139.24..2888067.19 rows=234 width=48) (actual time=5813.428..18345.362 rows=936 loops=1)

         Reduction: Local + Global

         GPU Projection: cat, ax

         Number of tasks: 468

         gpupreagg_main(): total: 621.04ms, avg: 1.33ms, count: 468

          - gpupreagg_preparation(): total: 148.50ms, avg: 0.32ms, count: 468

          - gpupreagg_local_reduction(): total: 309.76ms, avg: 0.66ms, count: 468

          - gpupreagg_global_reduction(): total: 98.48ms, avg: 0.21ms, count: 468

          - gpupreagg_final_reduction(): total: 50.33ms, avg: 0.11ms, count: 468

          - gpupreagg_fixup_varlena(): total: 0.07ms, avg: 0.02ms, count: 4

         Time of load: 16.47sec

         Time of materialize: 0.07ms

         DMA send: 9.71GB/sec, len: 7254.57MB, time: 729.75ms, count: 1404

         DMA recv: 3127.92MB/sec, len: 31.04MB, time: 9.92ms, count: 472

         ->  Custom Scan (GpuJoin) on t0  (cost=10139.24..2852814.83 rows=100000080 width=12) (actual time=78.421..16464.783 rows=100000000 loops=1)

               GPU Projection: t0.cat, t1.ax

               Outer Scan: t0 (actual time=10.089..3907.974 rows=100000000 loops=1)

               Depth 1: GpuHashJoin, HashKeys: (t0.aid)

                        JoinQuals: (t0.aid = t1.aid)

                        Nrows (in:100000000 out:100000000, 100.00% planned 100.00%)

                        KDS-Hash (size: 9.16MB planned 13.47MB, nbatches: 1 planned 1)

               Inner Buffer: (13.47MB), DMA nums: 250, size: 3367.94MB

               Number of tasks: 499

               gpujoin_main(): total: 1157.40ms, avg: 2.32ms, count: 499

                - gpujoin_exec_outerscan: total: 42.54ms, avg: 0.09ms, count: 499

                - gpujoin_exec_hashjoin: total: 546.90ms, avg: 1.10ms, count: 499

                - gpujoin_projection: total: 553.35ms, avg: 1.11ms, count: 499

               Time of inner load: 25.53ms

               Time of outer load: 7816.17ms

               Time of materialize: 4469.05ms

               DMA send: 10.04GB/sec, len: 7734.64MB, time: 751.97ms, count: 1497

               DMA recv: 9.69GB/sec, len: 7150.79MB, time: 720.59ms, count: 998

               ->  Seq Scan on t1  (cost=0.00..1935.00 rows=100000 width=12) (actual time=0.014..11.058 rows=100000 loops=1)

Planning time: 0.649 ms

Execution time: 18715.838 ms

(37 rows)

**Comment by kaigai** [comment]
It is not strange.

GpuPreAgg and below consumes 18.345s, and GpuJoin consumes 16.464s.
From the standpoint of GpuPreAgg, "time to load" includes entire time for GpuJoin, because the data stream has to be joined prior to GpuPreAgg execution.

On the other hands, GpuJoin consumes 7.8sec for outer load and 4.4sec to deliver the results to upper node (GpuPreAgg). So, actual time consumption by GpuJoin is about 4.2sec.
DMA send/recv consumes 1.5 in total, and GPU kernel execution consumes 1.2sec.
4.2 - 1.5 - 1.2 = 1.5sec are consumed by misc factor.

It looks to me this results is almost healthy.

**Comment by xuxilei** [comment]
but   1 GTX1080  OR  2 GTX1080 ,   the result is same
why?

**Comment by kaigai** [comment]
Which branch did you use? ```STABLE_v1```? or, ```master```?

In ver 1.0, a backend process tries to use multiple GPUs, but makes less sense because performance dominance factor is relation scan by CPU.

In ver 2.0 (```master```), a backend connects to a GPU server, and a GPU server use a GPU.
Your query execution plan does not use CPU parallel, thus, it uses either of GPUs.

If you want to utilize multiple GPUs, it needs to be CPU+GPU hybrid parallel.
Relation scan by CPU is much slower than DMA transfer / query execution by GPU.

**Comment by xuxilei** [comment]
http://www.infoq.com/cn/news/2015/09/PG-Storm
test of postgresql and pg-strom

you use GTX980(NEC Express5800),  I use GTX1080 . your result is 8.38s, my result 18.7s .  why?

**Comment by kaigai** [comment]
Did you preload entire dataset on the shared buffer?
Once i/o (or syscall for buffer copy) happen, it makes slow down.

In general, many factor determines performance results. GPU model is just one of them.

**Comment by xuxilei** [comment]
Would you tell me how to preload entire dataset on the shared buffer?

**Comment by kaigai** [comment]
https://www.postgresql.org/docs/devel/static/pgprewarm.html
