### ISSUE TITLE
Support for CC 3.0?

### ISSUE THREAD

**Issue by stenerikbjorling** [pg-strom/devel#275]
Is there a large development effort needed to support CC of 3.0? What functionalities might be sacrificed?

**Comment by kaigai** [comment]
Sorry, I'm not certain what CC means here.

C-Compiler? Common Criteria?

**Comment by skywalkerytx** [comment]
guess is Compute Capability

2017年5月24日 上午9:50，"KaiGai Kohei" <notifications@github.com>写道：

**Comment by stenerikbjorling** [comment]
Yes, it is Compute Capability of the Nvidia GPUs supported.

**Comment by kaigai** [comment]
Ah, Compute Capability.

Because of dynamic parallelism support, it is hard to support older GPUs than CC3.5.

Please assume a situation GpuJoin workloads on outer table ```t0``` and inner table ```t1``` and ```t2```.
We cannot know exact number of rows generated in results of join between ```t0``` and ```t1```,
therefore, it means nobody can give optimal number of threads to process join between (```t0```, ```t1```)
and ```t2```.
If number of threads would be too much larger than the number of (```t0```, ```t1```), majority of GPU
cores works for senseless tasks; launched then just exist after the check of number of rows.

In the older version of PG-Strom, we launched GPU kernel with speculative number of threads,
however, it didn't work well for many of real-life SQL queries.

Dynamic parallelism allows to control number of threads on the next step after the previous step
without interaction by CPU/Driver. It was a great advantage, and all the supported SQL workloads
(GpuScan, GpuJoin, and GpuPreAgg) now heavily use dynamic parallelism.

I like to recommend the latest generation of GPUs instead.

**Comment by stenerikbjorling** [comment]
Many thanks for your information - I will get my hands on a more modern GPU. Have some challenges compiling pg_strom on Mac now but I guess I will succeed putting some effort into it. The release of drivers for the Pascal generation opens up a number of possibilities for us pesky Mac-types... :-)

**Comment by kaigai** [comment]
BTW, one other nightmare of speculative resource management exists on allocation of device memory.

Pascal generation offers us a solution; demand paging on device memory if and when it is allocated
using managed memory allocation APIs.
Current version of PG-Strom allocates device memory speculatively, so it often causes out-of-buffer
error (if results are larger than estimated), or may consume larger than necessity (if results are smaller
than estimated).

So, I'm now under investigation of managed device memory use scenario for more efficient resource
usage. APIs itself are supported on CC3.5, however, CC6.x generation has actual demand paging,
and NVIDIA announced CC7.x has wise paging logic on hardware.

I'd like to recommend GPUs in Pascal generation (GTX10x0 series) for longer usage.

**Comment by stenerikbjorling** [comment]
Many thanks for this. I am in a proposal process for a project within circular economy in which we are planning to create information logistics structures for resource use and environmental impacts (P2P) which really can use this technology to cheaply implement powerful analytical functionality even in smaller installations. Take care, and thanks for your efforts... Might need support later for the compilation to Mac.

**Comment by kaigai** [comment]
Recent GPUs can likely work with PG-Strom, however, our recommendation is (1) more than 1600CUDA cores, (2) more than 4GB RAM and higher than 200GB/s memory band.
Some of them might not so cheap, but cost effective than equivalent computing capacity with CPUs....
https://github.com/pg-strom/devel/wiki/GPU-Availability-Matrix
