### ISSUE TITLE
Index hints and force caching an index/table to the GPU

### ISSUE THREAD

**Issue by jlehew** [pg-strom/devel#277]
The typical hardware architecture of a large server and has up to 12+ TB of server memory, but a GPU has 16 GB of memory each.  A large server has 10 PCIe slots but after other slots are allocated to NICs and other PCIe AIC, only 4 to 6 GPUs would be installed in a server.  This configuration would have 125 times less GPU memory than system memory.   Although the GPU has a hundred times more cores, it also has a hundred times less memory.  Or in other words, GPU memory is a limited resource like cache.  

Have you considered adding custom pg-strom hints into a query to determine what parts of the execution plan is processed by the GPU?  Or add a keyword like the CACHE keyword in Oracle to move a table into memory?

Adding hints and/or adding an index keyword to force tables and indexes into the GPU would allow a sql developer to control what parts of the plan is run in the GPU.

**Comment by kaigai** [comment]
We don't have any plan to extend SQL syntax.
Because PostgreSQL has no infrastructure to enhance custom syntax for extensions, this kind of enhancement may be able to utilize human's heuristics but takes a side-effect of patching.

Maybe, you misunderstand its executor's behavior. Even if a table has more than multiple terabytes, PG-Strom split it into multiple chunks per 32MB (in default setting), then kicks GPU kernel per chunk.
A chunk once processed by GPU kernel shall be released from the GPU memory, then re-used for another chunks to be processed next.
