### ISSUE TITLE
Graph and Varlena Alternative for +1GB data (Enhancements)

### ISSUE THREAD

**Issue by unibum** [pg-strom/devel#278]
Hello, Is there any benefit or opportunity to build graph capability (like OQGraph in MariaDb) into PGStrom? or no benefit in performance from GPU perspective?

Also, if so, would this benefit from sitting on top of PGStron v3.0 Columnar cache for faster performance, or not?

Also, in your article you speak of a Varlena +1Gb Data alternative, any progress on that patch for PG11? Close to being submitted?

**Comment by kaigai** [comment]
Sorry, at this moment, graph analytics is not a topic I'm working on with my priority.
So, here is no easy way to get acceleration by GPU now.
(You may need to implement PL/CUDA code by yourself. It is not an easy way.)

> Also, in your article you speak of a Varlena +1Gb Data alternative, any progress on that patch for PG11? Close to being submitted?

I'm inclined to another alternative idea instead of varlena beyond 1GB.
It tries to allocate a persistent GPU device memory, and allows to access users via foreign table.
This approach will not be prevented by 1GB varlena size limitation, and avoid time consumption by setting up argument for each PL/CUDA function invocation.
