### ISSUE TITLE
How to estimate the time spending on CPU and GPU?

### ISSUE THREAD

**Issue by davidzengxhsh** [pg-strom/devel#284]
In the master branch, the pg_strom.perfmon in removed. 
Then how to estimate the percentage of time spending on CPU side and GPU side? And the time spending on data transferring to/from GPU?

**Comment by kaigai** [comment]
```SET pg_strom.cuda_profiler = on``` allows to write out a bunch of CUDA visual profiler data to ```$PGDATA/cuda_profile.<GPU Num>.log```
![fig00](https://user-images.githubusercontent.com/216210/28147576-987c14ce-67bc-11e7-9166-9d788bc5bf8e.png)

The older (self implemented) profiling stuff cannot collect correct profiling under the CPU-parallel environment. For example, DMA throughput is shown much slower than actual one when multiple processes kicks DMA send/recv concurrently.

You can import this log file using (File)->(Import)->(Command-line Profiler) of CUDA visual profile

**Comment by kaigai** [comment]
As an aside, the latest master branch has a problem around scheduling of GPU tasks.... Now I'm under investigation.

**Comment by davidzengxhsh** [comment]
Thanks! 
I got a "ERROR:  Out of DMA buffer segment" crash with the latest code when running sql tasks simultaneously. Maybe this is the problem what you mentioned.

**Comment by kaigai** [comment]
Ah, it is issue of #281, although I put the case in Japanese for my convenience.
In case of parallel queries, it makes little sense to control number of concurrent GPU tasks using ```max_async_tasks``` per backend....

**Comment by exialin** [comment]
Hello master. As for v2.0, do we have any way to monitor GPU performance? I notice that there are some `CUevent` stuff in the code, but no statistics are collected?

**Comment by kaigai** [comment]
Since PostgreSQL v9.6 which support parallel query execution, we have no easy way to measure GPU usage in reliable way. (Even if a worker get slow throughput of DMA send/recv, it might mean other concurrent processes just use PCIe bus with full rate data transfer, and so on...)

A rough option is: `nvidia-smi -lms xxx` to display GPU usage at the moment.

One other option is nvidia visual profiler with `--profile-all-processes` under the same OS-user to PostgreSQL server.

But I tried the later option just moment before, `nvprof` raised uncertain error thus could not collect performance information right now.

**Comment by exialin** [comment]
I see... Although it is possible, the performance information tends to be inaccurate for a process. Thank you.
